dropCount: 2
swordPower: 3
smallHealth: 2d
middleHealth: 5d
hugeHealth: 10d
attackDelay: 1000
sword: "Excalibur"
shovel: "ShoutGun"
hoe: "Bazooka"
pickaxe: "Blaster"
boots: "Bashmachki"
chestplate: "NaGrudinin"
helmet: "Nabaldazhnik"
leggins: "40 griven"