dropCount: 2
swordPower: 3
smallHealth: 2
middleHealth: 5
hugeHealth: 10
attackDelay: 25
sword: "Excalibur"
shovel: "ShoutGun"
hoe: "Bazooka"
pickaxe: "Blaster"
boots: "Bashmachki"
chestplate: "NaGrudinin"
helmet: "Nabaldazhnik"
leggins: "40griven"