name: QuakeCraft
version: 0.1
author: Shakal
main: com.quake.Main
api-version: 1.13
commands:
  new:
    description: Craete blocks

permissions:
  creator:
    description: Only creator can change this map
    default: op

