name: QuakeCraft
version: 0.1
author: Shakal
main: com.quake.Main
api-version: 1.13
commands:
  newitemblock:
    description: Craete item block
  newjumpblock:
    description: Craete jump block
  newspawnblock:
    description: Craete spawn block
  remove:
    description: Remove block
  show:
    description: Show all blocks

permissions:
  creator:
    description: Only creator can change this map
    default: op

